---
- hosts: gcp-fw
  connection: local
  gather_facts: false

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Change admin password using SSH
      panos_admpwd:
        ip_address: '{{ provider.ip_address }}'
        username: '{{ provider.username }}'
        newpassword: '{{ provider.password }}'
        key_filename: '{{ private_key }}'
