---
- hosts: all
  connection: local
  gather_facts: false

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Change admin password using SSH
      panos_admpwd:
        ip_address: '{{ provider.ip_address }}'
        username: '{{ provider.username }}'
        newpassword: '{{ provider.password }}'
        key_filename: '{{ private_key }}'
      register: result
      until: result is not failed and (result.stdout | join('') | search('Configuration committed successfully'))
      retries: 10
      delay: 30
