---
- hosts: gcp-fw
  connection: local
  gather_facts: false

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Change admin password using SSH
      panos_admpwd:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        newpassword: '{{ password }}'
        key_filename: '{{ private_key }}'
